version: 1.0.{build}-{branch}

# https://www.appveyor.com/docs/branches/
branches:
  only:
    - master
    - develop
    - /features\/.+/ # Regular expressions should be surrounded by /, otherwise Appveyor will do simple case insensitive string comparison.

# skip_tags: true

image: Visual Studio 2017
# GitVersion need a proper git repo
# clone_depth: 1 
cache:
  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - src\packages -> **\packages.config  
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - ps: Write-Host "Hello from PowerShell"

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

for:
-
  branches:
    only:
      - master
  configuration: Release
- 
  branches:
    only:
      - develop
  configuration: Debug
- 
  branches:
    only:
      - /feature\/.+/ # Regular expressions should be surrounded by /, otherwise Appveyor will do simple case insensitive string comparison.
  configuration: Debug

before_build: 
  - nuget restore src\MoreTesting.sln

build:
  parallel: true                  # enable MSBuild parallel builds
  project: src\MoreTesting.sln     # path to Visual Studio solution or project

test: off

artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: src\MoreTesting.Wpf\bin\$(configuration) 
    name: MoreTesting.Wpf-$(configuration)
    # $(configuration) works here



