image: Visual Studio 2017

branches:
  only:
    - master
    - develop
    - /features\/.+/ # Regular expressions should be surrounded by /, otherwise Appveyor will do simple case insensitive string comparison.

cache:
  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - src\packages -> **\packages.config  
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

skip_tags: true

assembly_info:
  # handled by cake build script
  patch: false

# handled by cake build script
test: off

build_script:
  - ps: .\build.ps1 -Verbosity Diagnostic